package com.alag.agmall.business.module.notify.api.model;

import java.io.Serializable;
import java.util.Date;
import java.util.function.Consumer;
import java.util.function.Function;

public class NotifyRecordLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.id
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.version
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.update_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.create_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.notify_id
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.request
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String request;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.response
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.merchant_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String merchantNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.merchant_order_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String merchantOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record_log.http_status
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String httpStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.id
     *
     * @return the value of mmall_notify_record_log.id
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.id
     *
     * @param id the value for mmall_notify_record_log.id
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.version
     *
     * @return the value of mmall_notify_record_log.version
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.version
     *
     * @param version the value for mmall_notify_record_log.version
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.update_time
     *
     * @return the value of mmall_notify_record_log.update_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.update_time
     *
     * @param updateTime the value for mmall_notify_record_log.update_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.create_time
     *
     * @return the value of mmall_notify_record_log.create_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.create_time
     *
     * @param createTime the value for mmall_notify_record_log.create_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.notify_id
     *
     * @return the value of mmall_notify_record_log.notify_id
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.notify_id
     *
     * @param notifyId the value for mmall_notify_record_log.notify_id
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId == null ? null : notifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.request
     *
     * @return the value of mmall_notify_record_log.request
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.request
     *
     * @param request the value for mmall_notify_record_log.request
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setRequest(String request) {
        this.request = request == null ? null : request.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.response
     *
     * @return the value of mmall_notify_record_log.response
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.response
     *
     * @param response the value for mmall_notify_record_log.response
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.merchant_no
     *
     * @return the value of mmall_notify_record_log.merchant_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.merchant_no
     *
     * @param merchantNo the value for mmall_notify_record_log.merchant_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.merchant_order_no
     *
     * @return the value of mmall_notify_record_log.merchant_order_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.merchant_order_no
     *
     * @param merchantOrderNo the value for mmall_notify_record_log.merchant_order_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo == null ? null : merchantOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record_log.http_status
     *
     * @return the value of mmall_notify_record_log.http_status
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getHttpStatus() {
        return httpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record_log.http_status
     *
     * @param httpStatus the value for mmall_notify_record_log.http_status
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setHttpStatus(String httpStatus) {
        this.httpStatus = httpStatus == null ? null : httpStatus.trim();
    }

    public void setFields(Consumer<NotifyRecordLog> consumer) {
        consumer.accept(this);
    }


    public static NotifyRecordLog setReturn(Function<NotifyRecordLog, NotifyRecordLog> function) {
        return function.apply(new NotifyRecordLog());
    }
}