package com.alag.agmall.business.module.notify.api.model;

import lombok.ToString;

import java.io.Serializable;
import java.util.Date;
import java.util.function.Consumer;
import java.util.function.Function;

@ToString
public class NotifyRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.id
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.version
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.create_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.update_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.notify_rule
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String notifyRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.notify_times
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Integer notifyTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.limit_notify_times
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Integer limitNotifyTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.url
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.merchant_order_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String merchantOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.merchant_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private String merchantNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.status
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_notify_record.notify_type
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    private Integer notifyType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.id
     *
     * @return the value of mmall_notify_record.id
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.id
     *
     * @param id the value for mmall_notify_record.id
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.version
     *
     * @return the value of mmall_notify_record.version
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.version
     *
     * @param version the value for mmall_notify_record.version
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.create_time
     *
     * @return the value of mmall_notify_record.create_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.create_time
     *
     * @param createTime the value for mmall_notify_record.create_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.update_time
     *
     * @return the value of mmall_notify_record.update_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.update_time
     *
     * @param updateTime the value for mmall_notify_record.update_time
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.notify_rule
     *
     * @return the value of mmall_notify_record.notify_rule
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getNotifyRule() {
        return notifyRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.notify_rule
     *
     * @param notifyRule the value for mmall_notify_record.notify_rule
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setNotifyRule(String notifyRule) {
        this.notifyRule = notifyRule == null ? null : notifyRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.notify_times
     *
     * @return the value of mmall_notify_record.notify_times
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Integer getNotifyTimes() {
        return notifyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.notify_times
     *
     * @param notifyTimes the value for mmall_notify_record.notify_times
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setNotifyTimes(Integer notifyTimes) {
        this.notifyTimes = notifyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.limit_notify_times
     *
     * @return the value of mmall_notify_record.limit_notify_times
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Integer getLimitNotifyTimes() {
        return limitNotifyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.limit_notify_times
     *
     * @param limitNotifyTimes the value for mmall_notify_record.limit_notify_times
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setLimitNotifyTimes(Integer limitNotifyTimes) {
        this.limitNotifyTimes = limitNotifyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.url
     *
     * @return the value of mmall_notify_record.url
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.url
     *
     * @param url the value for mmall_notify_record.url
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.merchant_order_no
     *
     * @return the value of mmall_notify_record.merchant_order_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.merchant_order_no
     *
     * @param merchantOrderNo the value for mmall_notify_record.merchant_order_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo == null ? null : merchantOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.merchant_no
     *
     * @return the value of mmall_notify_record.merchant_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.merchant_no
     *
     * @param merchantNo the value for mmall_notify_record.merchant_no
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.status
     *
     * @return the value of mmall_notify_record.status
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.status
     *
     * @param status the value for mmall_notify_record.status
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_notify_record.notify_type
     *
     * @return the value of mmall_notify_record.notify_type
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public Integer getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_notify_record.notify_type
     *
     * @param notifyType the value for mmall_notify_record.notify_type
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    public void setNotifyType(Integer notifyType) {
        this.notifyType = notifyType;
    }

    public static NotifyRecord setReturn(Function<NotifyRecord,NotifyRecord> function) {
        return function.apply(new NotifyRecord());
    }

    public void setFields(Consumer<NotifyRecord> consumer) {
        consumer.accept(this);
    }

}