eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 30
  client:
    registryFetchIntervalSeconds: 30
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://47.240.11.229:8761/eureka
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试