zserver:
  port: 8098
spring:
  redis:
    database: 0
    host: 47.240.11.229
    port: 6379
    password: 123456
    timeout: 2000ms
    store-type: redis
  application:
    name: app-maxnotify
  profiles:
    active: dev
#初始化InitNotifyParam的属性
notifyparam:
  successValue: SUCCESS
  notifyTimeMaps:
    1: 1
    2: 2
    3: 3
    4: 10
    5: 15
