package com.alag.agmall.business.module.notify.server.mapper;

import com.alag.agmall.business.core.page.NotifyPageParamBean;
import com.alag.agmall.business.module.notify.api.model.NotifyRecord;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface NotifyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_notify_record
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_notify_record
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    int insert(NotifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_notify_record
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    int insertSelective(NotifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_notify_record
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    NotifyRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_notify_record
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    int updateByPrimaryKeySelective(NotifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_notify_record
     *
     * @mbggenerated Sat Aug 17 15:02:22 CST 2019
     */
    int updateByPrimaryKey(NotifyRecord record);

    NotifyRecord selectByCondition(@Param("merchantNo") String merchantNo,
                                   @Param("merchantOrderNo")String merchantOrderNo,
                                   @Param("notifyType")String notifyType);

    List<NotifyRecord> selectListByCondition(NotifyPageParamBean notifyPageParamBean);
}