package com.alag.agmall.business.module.alipay.api.model;

import lombok.ToString;

import java.io.Serializable;
import java.util.Date;
import java.util.function.Consumer;
@ToString
public class AlipayInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_alipay.id
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_alipay.user_id
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_alipay.order_no
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_alipay.trade_no
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_alipay.trade_status
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    private String tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_alipay.gmt_payment
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    private Date gmtPayment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_alipay.id
     *
     * @return the value of mmall_alipay.id
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_alipay.id
     *
     * @param id the value for mmall_alipay.id
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_alipay.user_id
     *
     * @return the value of mmall_alipay.user_id
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_alipay.user_id
     *
     * @param userId the value for mmall_alipay.user_id
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_alipay.order_no
     *
     * @return the value of mmall_alipay.order_no
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_alipay.order_no
     *
     * @param orderNo the value for mmall_alipay.order_no
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_alipay.trade_no
     *
     * @return the value of mmall_alipay.trade_no
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_alipay.trade_no
     *
     * @param tradeNo the value for mmall_alipay.trade_no
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_alipay.trade_status
     *
     * @return the value of mmall_alipay.trade_status
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_alipay.trade_status
     *
     * @param tradeStatus the value for mmall_alipay.trade_status
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_alipay.gmt_payment
     *
     * @return the value of mmall_alipay.gmt_payment
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public Date getGmtPayment() {
        return gmtPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_alipay.gmt_payment
     *
     * @param gmtPayment the value for mmall_alipay.gmt_payment
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    public void setGmtPayment(Date gmtPayment) {
        this.gmtPayment = gmtPayment;
    }

    public static AlipayInfo setReturn(Consumer<AlipayInfo> consumer) {
        AlipayInfo alipayInfo = new AlipayInfo();
        consumer.accept(alipayInfo);
        return alipayInfo;
    }
}