package com.alag.agmall.business.module.message.server.mapper;

import com.alag.agmall.business.core.page.ParamBean;
import com.alag.agmall.business.module.message.api.model.TransactionMessage;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TransactionMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_transaction_message
     *
     * @mbggenerated Fri Aug 09 08:36:08 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_transaction_message
     *
     * @mbggenerated Fri Aug 09 08:36:08 CST 2019
     */
    int insert(TransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_transaction_message
     *
     * @mbggenerated Fri Aug 09 08:36:08 CST 2019
     */
    int insertSelective(TransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_transaction_message
     *
     * @mbggenerated Fri Aug 09 08:36:08 CST 2019
     */
    TransactionMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_transaction_message
     *
     * @mbggenerated Fri Aug 09 08:36:08 CST 2019
     */
    int updateByPrimaryKeySelective(TransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_transaction_message
     *
     * @mbggenerated Fri Aug 09 08:36:08 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_transaction_message
     *
     * @mbggenerated Fri Aug 09 08:36:08 CST 2019
     */
    int updateByPrimaryKey(TransactionMessage record);

    TransactionMessage getByMessageId(String messageId);

    void delByMsgId(String messageId);

    List<TransactionMessage> selectByQueueName(String queueName);

    List<TransactionMessage> list(ParamBean paramBean);
}