package com.alag.agmall.business.module.alipay.server.mapper;

import com.alag.agmall.business.module.alipay.api.model.AlipayInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AlipayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_alipay
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_alipay
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    int insert(AlipayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_alipay
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    int insertSelective(AlipayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_alipay
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    AlipayInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_alipay
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    int updateByPrimaryKeySelective(AlipayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_alipay
     *
     * @mbggenerated Tue Aug 13 12:03:20 CST 2019
     */
    int updateByPrimaryKey(AlipayInfo record);

    AlipayInfo selectByOrderNo(Long orderNo);
}